name: OpenFGA test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: public.ecr.aws/docker/library/postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OpenFGA migration
        run: |
          docker run --rm \
            --network host \
            -e OPENFGA_DATASTORE_ENGINE=postgres \
            -e OPENFGA_DATASTORE_URI=postgres://postgres:password@127.0.0.1:5432/postgres?sslmode=disable \
            openfga/openfga:v1.8.13 migrate

      - name: Run OpenFGA server
        run: |
          docker run --rm -d \
            --network host \
            --name openfga-server \
            -p 8080:8080 \
            -e OPENFGA_DATASTORE_ENGINE=postgres \
            -e OPENFGA_DATASTORE_URI=postgres://postgres:password@127.0.0.1:5432/postgres?sslmode=disable \
            -e OPENFGA_LOG_FORMAT=json \
            openfga/openfga:v1.8.13 run

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Run tests
        run: |
          go test -shuffle on ./...
        env:
          FGA_API_URL: http://127.0.0.1:8080

      - name: Stop OpenFGA server
        run: |
          docker stop openfga-server
